### ISSUE TITLE
Package install issues with R 4.4.1 due to outdated dependencies?

### ISSUE THREAD

**Issue by aburtis** [amc-heme/SCUBA#101]
Some of the packages needed for SCUBA installation are out of date for the newest version of R. This therefore creates and error and a nonzero exit when trying to install SCUBA. The packages in the warning are: 'SummarizedExperiment', 'HDF5Array', and 'SingleCellExperiment'.  If they are installed with bioconductor (newest version of each package), then SCUBA is able to be installed. But simply trying to install SCUBA in R 4.4.1 causes the following error.

ERROR: dependencies ‘SingleCellExperiment’, ‘HDF5Array’, ‘SummarizedExperiment’ are not available for package ‘SCUBA’
* removing '/R/x86_64-pc-linux-gnu-library/4.4/SCUBA’
Warning messages:
1: packages ‘SummarizedExperiment’, ‘HDF5Array’, ‘SingleCellExperiment’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by kengel001** [comment]
I had this happen as well, those need to be installed separately for now. @wish1832 is going to change how the install happens so those get installed if they aren't already.

**Comment by agillen** [comment]
This can be solved with `BiocManager::install("amc-heme/scuba", dependencies = T)`

**Comment by agillen** [comment]
Per the Bioconductor Team, this is the correct way to install non-bioconductor packages with bioconductor deps.

**Comment by wish1832** [comment]
The docs were updated to recommend installing in this way (#99, #102).
