### ISSUE TITLE
Create function to display unique metadata values

### ISSUE THREAD

**Issue by wish1832** [amc-heme/SCUBA#48]
In scExploreR, a common operation is to display all unique values from a metadata variable. Since this may be useful to those using SCEPlots as a API for plotting, it is reasonable to implement a function in SCEPlots to be called in scExploreR. The function will use the fetch_metadata generic defined in this package (Issue related to amc-heme/scExploreR#221).

**Comment by jairav** [comment]
completed in https://github.com/amc-heme/SCUBA/commit/990a7d10522a9e555953307dd855070f2e4949d3
