### ISSUE TITLE
Error in reduction plot for non-UMAP reductions

### ISSUE THREAD

**Issue by wish1832** [amc-heme/SCUBA#52]
When attempting to plot via plot_reduction, the following error was observed:

```
plot_reduction(
  object = object,
  group_by = "ab200_clusters",
  reduction = "TOTALVI_LNGB"
  )
```

`Error: The dimensions requested were not found.`

The function works fine when the reduction plotted is a UMAP.  The error appears to occur for all non-UMAP reductions.

```
plot_reduction(
  object = object,
  group_by = "ab200_clusters",
  reduction = "UMAP"
  )
```

**Comment by jairav** [comment]
This should be addressed in the plotting package, and a test written for it.
