### ISSUE TITLE
Improper handling of non-existent reductions in reduction plot

### ISSUE THREAD

**Issue by wish1832** [amc-heme/SCUBA#53]
When passing a reduction that does not exist to plot_reduction, the error is not properly handled:

```
plot_reduction(
   object = sce_3,
   group_by = "ab200_clusters",
   reduction = "TOTALVI"
  )
```
`Error in data.frame(..., check.names = FALSE) :
arguments imply differing number of rows: 0, 200548` 

A more specific error message should be returned in this case.

**Comment by jairav** [comment]
Needs to be addressed/tested in plotting package (scPlots).
